apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
spec:
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
          - containerPort: 80
      envFrom:
        - configMapRef:
          name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: app