apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: nginx-statefulset
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
      spec:
        containers:
          - name: nginx-container
            image: nginx:stable
            ports:
              - containerPort: 80
            envFrom:
              - configMapRef:
                  name: db-configmap

  selector:
    matchLabels:
      app: nginx-pod
  serviceName: svc-load-balancer