apiVersion: v1
kind: Pod
metadata:
  name: Meu segundo Pod
  labels:
    app: segundo-pod
spec:
  containers:
    - name: mongo-container
      image: mongo:latest
      ports:
        - containerPort: 27017